# Generated by Django 3.1.3 on 2022-03-28 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessClientProfileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(blank=True, max_length=50, null=True)),
                ('business_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('business_email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClientAddressModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ClientPaymentInfoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(blank=True, choices=[('CASH', 'CASH'), ('CHECQUE', 'CHECQUE'), ('CREDIT CARD', 'CREDIT CARD'), ('INVOICE', 'INVOICE')], max_length=60, null=True)),
                ('card_name', models.CharField(blank=True, max_length=50, null=True)),
                ('card_number', models.CharField(blank=True, max_length=50, null=True)),
                ('card_expiration_date', models.CharField(blank=True, max_length=20, null=True)),
                ('cvv', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MerchantAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_id', models.CharField(blank=True, max_length=100, null=True)),
                ('chosen_payment_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalClientProfileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_phone', models.CharField(max_length=20)),
                ('secondary_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('is_client_active', models.BooleanField(blank=True, default=True, null=True, verbose_name='Create LC Account')),
                ('is_corporate_client', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('business_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Client.businessclientprofilemodel')),
                ('client_payment_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Client.clientpaymentinfomodel')),
            ],
        ),
    ]
