# Generated by Django 3.1.3 on 2022-03-28 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Company', '0001_initial'),
        ('setting', '0001_initial'),
        ('Employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrakeTyre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brakes', models.CharField(blank=True, choices=[('Satisfactory', 'Satisfactory'), ('Unsatisfactory', 'Unsatisfactory'), ('Good', 'Good'), ('Refilled', 'Refilled'), ('Replaced', 'Replaced')], default='Satisfactory', max_length=20, null=True)),
                ('rims', models.CharField(blank=True, choices=[('Satisfactory', 'Satisfactory'), ('Unsatisfactory', 'Unsatisfactory'), ('Good', 'Good'), ('Refilled', 'Refilled'), ('Replaced', 'Replaced')], default='Satisfactory', max_length=20, null=True)),
                ('tyres', models.CharField(blank=True, choices=[('Satisfactory', 'Satisfactory'), ('Unsatisfactory', 'Unsatisfactory'), ('Good', 'Good'), ('Refilled', 'Refilled'), ('Replaced', 'Replaced')], default='Satisfactory', max_length=20, null=True)),
                ('wear', models.CharField(blank=True, choices=[('Satisfactory', 'Satisfactory'), ('Unsatisfactory', 'Unsatisfactory'), ('Good', 'Good'), ('Refilled', 'Refilled'), ('Replaced', 'Replaced')], default='Satisfactory', max_length=20, null=True)),
                ('break_comments', models.TextField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fluid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anti_freeze', models.CharField(blank=True, choices=[('Satisfactory', 'Satisfactory'), ('Unsatisfactory', 'Unsatisfactory'), ('Good', 'Good'), ('Refilled', 'Refilled'), ('Replaced', 'Replaced')], default='Satisfactory', max_length=20, null=True)),
                ('brake_fluid', models.CharField(blank=True, choices=[('Satisfactory', 'Satisfactory'), ('Unsatisfactory', 'Unsatisfactory'), ('Good', 'Good'), ('Refilled', 'Refilled'), ('Replaced', 'Replaced')], default='Satisfactory', max_length=20, null=True)),
                ('oil_level', models.CharField(blank=True, choices=[('Satisfactory', 'Satisfactory'), ('Unsatisfactory', 'Unsatisfactory'), ('Good', 'Good'), ('Refilled', 'Refilled'), ('Replaced', 'Replaced')], default='Satisfactory', max_length=20, null=True)),
                ('ps_fluid', models.CharField(blank=True, choices=[('Satisfactory', 'Satisfactory'), ('Unsatisfactory', 'Unsatisfactory'), ('Good', 'Good'), ('Refilled', 'Refilled'), ('Replaced', 'Replaced')], default='Satisfactory', max_length=20, null=True)),
                ('washer_fluid', models.CharField(blank=True, choices=[('Satisfactory', 'Satisfactory'), ('Unsatisfactory', 'Unsatisfactory'), ('Good', 'Good'), ('Refilled', 'Refilled'), ('Replaced', 'Replaced')], default='Satisfactory', max_length=20, null=True)),
                ('fluid_comments', models.TextField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GeneralVehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40, null=True, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/allvehicles')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Company.companyprofilemodel')),
            ],
        ),
        migrations.CreateModel(
            name='Light',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headlights_Lo', models.CharField(blank=True, choices=[('Satisfactory', 'Satisfactory'), ('Unsatisfactory', 'Unsatisfactory'), ('Good', 'Good'), ('Refilled', 'Refilled'), ('Replaced', 'Replaced')], default='Satisfactory', max_length=20, null=True)),
                ('headlights_Hi', models.CharField(blank=True, choices=[('Satisfactory', 'Satisfactory'), ('Unsatisfactory', 'Unsatisfactory'), ('Good', 'Good'), ('Refilled', 'Refilled'), ('Replaced', 'Replaced')], default='Satisfactory', max_length=20, null=True)),
                ('turn_signal_Lt', models.CharField(blank=True, choices=[('Satisfactory', 'Satisfactory'), ('Unsatisfactory', 'Unsatisfactory'), ('Good', 'Good'), ('Refilled', 'Refilled'), ('Replaced', 'Replaced')], default='Satisfactory', max_length=20, null=True)),
                ('turn_signal_Rt', models.CharField(blank=True, choices=[('Satisfactory', 'Satisfactory'), ('Unsatisfactory', 'Unsatisfactory'), ('Good', 'Good'), ('Refilled', 'Refilled'), ('Replaced', 'Replaced')], default='Satisfactory', max_length=20, null=True)),
                ('hazard_lights', models.CharField(blank=True, choices=[('Satisfactory', 'Satisfactory'), ('Unsatisfactory', 'Unsatisfactory'), ('Good', 'Good'), ('Refilled', 'Refilled'), ('Replaced', 'Replaced')], default='Satisfactory', max_length=20, null=True)),
                ('Interior_lights', models.CharField(blank=True, choices=[('Satisfactory', 'Satisfactory'), ('Unsatisfactory', 'Unsatisfactory'), ('Good', 'Good'), ('Refilled', 'Refilled'), ('Replaced', 'Replaced')], default='Satisfactory', max_length=20, null=True)),
                ('brake_lights', models.CharField(blank=True, choices=[('Satisfactory', 'Satisfactory'), ('Unsatisfactory', 'Unsatisfactory'), ('Good', 'Good'), ('Refilled', 'Refilled'), ('Replaced', 'Replaced')], default='Satisfactory', max_length=20, null=True)),
                ('light_comments', models.TextField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Misc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doors', models.CharField(blank=True, choices=[('Satisfactory', 'Satisfactory'), ('Unsatisfactory', 'Unsatisfactory'), ('Good', 'Good'), ('Refilled', 'Refilled'), ('Replaced', 'Replaced')], default='Satisfactory', max_length=20, null=True)),
                ('heater', models.CharField(blank=True, choices=[('Satisfactory', 'Satisfactory'), ('Unsatisfactory', 'Unsatisfactory'), ('Good', 'Good'), ('Refilled', 'Refilled'), ('Replaced', 'Replaced')], default='Satisfactory', max_length=20, null=True)),
                ('horn', models.CharField(blank=True, choices=[('Satisfactory', 'Satisfactory'), ('Unsatisfactory', 'Unsatisfactory'), ('Good', 'Good'), ('Refilled', 'Refilled'), ('Replaced', 'Replaced')], default='Satisfactory', max_length=20, null=True)),
                ('mirrors', models.CharField(blank=True, choices=[('Satisfactory', 'Satisfactory'), ('Unsatisfactory', 'Unsatisfactory'), ('Good', 'Good'), ('Refilled', 'Refilled'), ('Replaced', 'Replaced')], default='Satisfactory', max_length=20, null=True)),
                ('seats', models.CharField(blank=True, choices=[('Satisfactory', 'Satisfactory'), ('Unsatisfactory', 'Unsatisfactory'), ('Good', 'Good'), ('Refilled', 'Refilled'), ('Replaced', 'Replaced')], default='Satisfactory', max_length=20, null=True)),
                ('seat_belts', models.CharField(blank=True, choices=[('Satisfactory', 'Satisfactory'), ('Unsatisfactory', 'Unsatisfactory'), ('Good', 'Good'), ('Refilled', 'Refilled'), ('Replaced', 'Replaced')], default='Satisfactory', max_length=20, null=True)),
                ('steering', models.CharField(blank=True, choices=[('Satisfactory', 'Satisfactory'), ('Unsatisfactory', 'Unsatisfactory'), ('Good', 'Good'), ('Refilled', 'Refilled'), ('Replaced', 'Replaced')], default='Satisfactory', max_length=20, null=True)),
                ('windows', models.CharField(blank=True, choices=[('Satisfactory', 'Satisfactory'), ('Unsatisfactory', 'Unsatisfactory'), ('Good', 'Good'), ('Refilled', 'Refilled'), ('Replaced', 'Replaced')], default='Satisfactory', max_length=20, null=True)),
                ('windshield', models.CharField(blank=True, choices=[('Satisfactory', 'Satisfactory'), ('Unsatisfactory', 'Unsatisfactory'), ('Good', 'Good'), ('Refilled', 'Refilled'), ('Replaced', 'Replaced')], default='Satisfactory', max_length=20, null=True)),
                ('wiperblades', models.CharField(blank=True, choices=[('Satisfactory', 'Satisfactory'), ('Unsatisfactory', 'Unsatisfactory'), ('Good', 'Good'), ('Refilled', 'Refilled'), ('Replaced', 'Replaced')], default='Satisfactory', max_length=20, null=True)),
                ('misc_comments', models.TextField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('make', models.CharField(max_length=50)),
                ('is_on_ride', models.BooleanField(default=False)),
                ('model_name', models.CharField(max_length=50, verbose_name='Model')),
                ('year', models.CharField(max_length=15)),
                ('license', models.CharField(max_length=40)),
                ('plate_number', models.CharField(max_length=50, unique=True)),
                ('vehicle_number', models.CharField(max_length=30, unique=True)),
                ('color', models.CharField(max_length=50)),
                ('vin', models.CharField(max_length=17, unique=True, verbose_name='VIN')),
                ('insurance_company', models.CharField(max_length=50)),
                ('tabs_expiration_date', models.CharField(max_length=30, verbose_name='Registration expiration date')),
                ('inspection_expiration_date', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('milage', models.IntegerField(blank=True, null=True, verbose_name='Mileage')),
                ('last_ride_started_milage', models.IntegerField(blank=True, null=True)),
                ('last_ride_ending_milage', models.IntegerField(blank=True, null=True)),
                ('all_vehicle_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Vehicle.generalvehicle', verbose_name='Vehicle Name')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Company.companyprofilemodel')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Employee.employeeprofilemodel')),
                ('vehicle_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='setting.vehicletype', verbose_name='Vehicle Type')),
            ],
        ),
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other', models.TextField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brake_and_tyres', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Vehicle.braketyre')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Employee.employeeprofilemodel')),
                ('fluids', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Vehicle.fluid')),
                ('lights', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Vehicle.light')),
                ('misc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Vehicle.misc')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Vehicle.vehicle')),
            ],
        ),
    ]
