# Generated by Django 3.2.4 on 2022-07-19 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='quarter',
            new_name='quarters',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='week',
            new_name='weeks',
        ),
    ]
