# Generated by Django 3.2.4 on 2022-07-19 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0002_auto_20220720_0151'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='months',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
