# Generated by Django 4.2.16 on 2024-11-04 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0003_course_months'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='application_fee',
            field=models.IntegerField(blank=True, default=250, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='commission',
            field=models.IntegerField(blank=True, default=30, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='discount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='gst_status',
            field=models.CharField(blank=True, choices=[('NO COMMISSION', 'NO COMMISSION'), ('COMMISSION ONLY', 'COMMISSION ONLY'), ('COMMISSION + GST (10%)', 'COMMISSION + GST (10%)')], default='COMMISSION ONLY', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='material_fee',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='oshc',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='quarterly_fee_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='total_commission_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='total_fee',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='tuition_fee',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
