# Generated by Django 4.2.16 on 2024-11-04 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0004_course_application_fee_course_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='application_fee',
        ),
        migrations.RemoveField(
            model_name='course',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='course',
            name='commission',
        ),
        migrations.RemoveField(
            model_name='course',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='course',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='course',
            name='gst_status',
        ),
        migrations.RemoveField(
            model_name='course',
            name='material_fee',
        ),
        migrations.RemoveField(
            model_name='course',
            name='oshc',
        ),
        migrations.RemoveField(
            model_name='course',
            name='quarterly_fee_amount',
        ),
        migrations.RemoveField(
            model_name='course',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='course',
            name='total_commission_amount',
        ),
        migrations.RemoveField(
            model_name='course',
            name='total_fee',
        ),
        migrations.RemoveField(
            model_name='course',
            name='tuition_fee',
        ),
    ]
