# Generated by Django 3.2.4 on 2022-04-19 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agent', '0002_alter_agentmodel_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentmodel',
            name='bonus',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
