# Generated by Django 3.2.4 on 2022-04-19 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agent', '0003_agentmodel_bonus'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentmodel',
            name='commission',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
