# Generated by Django 3.2.4 on 2022-04-19 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agent', '0004_agentmodel_commission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentmodel',
            name='commission',
            field=models.IntegerField(blank=True, default=30, null=True),
        ),
    ]
