# Generated by Django 3.1.3 on 2022-04-19 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agent', '0005_alter_agentmodel_commission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentmodel',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
