# Generated by Django 3.2.4 on 2022-04-22 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agent', '0006_auto_20220419_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentmodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
