# Generated by Django 3.2.4 on 2022-04-26 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0032_auto_20220426_2042'),
        ('Agent', '0009_commissionmodelagent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commissionmodelagent',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Student.studentmodel'),
        ),
    ]
