# Generated by Django 3.2.4 on 2022-04-26 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Agent', '0010_alter_commissionmodelagent_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commissionmodelagent',
            name='commission_left',
        ),
    ]
