# Generated by Django 3.2.4 on 2022-04-30 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Agent', '0011_remove_commissionmodelagent_commission_left'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commissionmodelagent',
            old_name='agent_commission_amount',
            new_name='paid_commission',
        ),
        migrations.RemoveField(
            model_name='commissionmodelagent',
            name='agent_commission_percentage',
        ),
        migrations.RemoveField(
            model_name='commissionmodelagent',
            name='current_commission_amount',
        ),
        migrations.RemoveField(
            model_name='commissionmodelagent',
            name='student_paid_fee',
        ),
        migrations.RemoveField(
            model_name='commissionmodelagent',
            name='total_commission_paid',
        ),
    ]
