# Generated by Django 3.2.4 on 2022-04-30 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agent', '0012_auto_20220430_0432'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commissionmodelagent',
            old_name='paid_commission',
            new_name='agent_commission_amount',
        ),
        migrations.AddField(
            model_name='commissionmodelagent',
            name='agent_commission_percentage',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='commissionmodelagent',
            name='current_commission_amount',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='commissionmodelagent',
            name='student_paid_fee',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='commissionmodelagent',
            name='total_commission_paid',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
