# Generated by Django 3.2.4 on 2022-07-03 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agent', '0016_auto_20220703_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentmodel',
            name='gst',
            field=models.CharField(blank=True, default=10, max_length=10, null=True),
        ),
    ]
