# Generated by Django 3.2.4 on 2022-07-20 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agent', '0019_alter_agentmodel_gst'),
    ]

    operations = [
        migrations.AddField(
            model_name='commissionmodelagent',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
