# Generated by Django 3.2.4 on 2022-08-02 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agent', '0021_commissionmodelagent_mode_of_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commissionmodelagent',
            name='mode_of_payment',
            field=models.CharField(blank=True, choices=[('CASH', 'CASH'), ('BANK TRANSFER', 'BANK TRANSFER'), ('UPFRONT FEE', 'UPFRONT FEE'), ('ADJUSTMENT', 'ADJUSTMENT')], max_length=100, null=True),
        ),
    ]
