# Generated by Django 3.2.4 on 2022-08-05 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agent', '0023_auto_20220803_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentmodel',
            name='gst_status',
            field=models.CharField(blank=True, choices=[('COMMISSION ONLY', 'COMMISSION ONLY'), ('COMMISSION + GST (10%)', 'COMMISSION + GST (10%)')], default='COMMISSION ONLY', max_length=30, null=True),
        ),
    ]
