# Generated by Django 4.2.16 on 2024-10-07 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agent', '0025_auto_20220807_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commissionmodelagent',
            name='mode_of_payment',
            field=models.CharField(blank=True, choices=[('CASH', 'CASH'), ('BANK TRANSFER', 'BANK TRANSFER'), ('UPFRONT COMMISSION', 'UPFRONT COMMISSION'), ('ADJUSTMENT', 'ADJUSTMENT')], max_length=100, null=True),
        ),
    ]
