# Generated by Django 4.2.16 on 2024-10-15 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agent', '0026_alter_commissionmodelagent_mode_of_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentmodel',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agentmodel',
            name='archived_tag',
            field=models.CharField(blank=True, choices=[('OnShore', 'OnShore'), ('Offshore', 'Offshore')], max_length=50, null=True),
        ),
    ]
