# Generated by Django 4.2.16 on 2024-11-11 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0070_alter_studentcourse_commission_to_pay'),
        ('Agent', '0027_agentmodel_archived_agentmodel_archived_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commissionmodelagent',
            name='student',
        ),
        migrations.AddField(
            model_name='commissionmodelagent',
            name='student_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Student.studentcourse'),
        ),
    ]
