# Generated by Django 3.1.3 on 2022-04-03 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0003_auto_20220402_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='date',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='time',
        ),
    ]
