# Generated by Django 3.1.3 on 2022-04-03 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0004_auto_20220403_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
