# Generated by Django 3.1.3 on 2022-04-03 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0005_auto_20220403_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Restaurant.restaurantmodel'),
        ),
    ]
