# Generated by Django 3.1.3 on 2022-04-03 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0006_expense_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantmodel',
            name='sales_tax',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
