# Generated by Django 3.1.3 on 2022-04-03 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0007_restaurantmodel_sales_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantmodel',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurantmodel',
            name='updated_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='restaurantmodel',
            name='last_paid_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
