# Generated by Django 3.1.3 on 2022-03-28 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Client', '0001_initial'),
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyAddressModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zip_code', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CompanyPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(null=True)),
                ('ends_at', models.DateTimeField(null=True)),
                ('trail_ends_at', models.DateTimeField(null=True)),
                ('is_on_trail', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('is_included', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_holder_name', models.CharField(max_length=100, null=True)),
                ('card_number', models.CharField(max_length=16, null=True)),
                ('expiry_month', models.IntegerField(choices=[('', 'MM'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], help_text='Expiry month', null=True)),
                ('expiry_year', models.IntegerField(choices=[('', 'YYYY'), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026), (2027, 2027), (2028, 2028), (2029, 2029), (2030, 2030), (2031, 2031), (2032, 2032), (2033, 2033), (2034, 2034), (2035, 2035), (2036, 2036)], help_text='Expiry year', null=True)),
                ('security_code', models.CharField(help_text='CVV', max_length=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('price', models.FloatField(default=0.0, null=True)),
                ('allowed_trips', models.IntegerField(default=0, null=True)),
                ('pricing_duration', models.CharField(choices=[('monthly', 'monthly'), ('yearly', 'yearly')], max_length=50, null=True)),
                ('short_description', models.TextField(help_text='You can add html as well', max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('features', models.ManyToManyField(related_name='package_features', to='Company.Feature')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyProfileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('secondary_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('distance_unit', models.CharField(max_length=50, null=True)),
                ('currency', models.CharField(max_length=10, null=True)),
                ('timezone', models.CharField(blank=True, choices=[('America/New_York', 'America/New_York'), ('America/Detroit', 'America/Detroit'), ('America/Kentucky/Louisville', 'America/Kentucky/Louisville'), ('America/Kentucky/Monticello', 'America/Kentucky/Monticello'), ('America/Indiana/Indianapolis', 'America/Indiana/Indianapolis'), ('America/Indiana/Vincennes', 'America/Indiana/Vincennes'), ('America/Indiana/Winamac', 'America/Indiana/Winamac'), ('America/Indiana/Marengo', 'America/Indiana/Marengo'), ('America/Indiana/Petersburg', 'America/Indiana/Petersburg'), ('America/Indiana/Vevay', 'America/Indiana/Vevay'), ('America/Chicago', 'America/Chicago'), ('America/Indiana/Tell_City', 'America/Indiana/Tell_City'), ('America/Indiana/Knox', 'America/Indiana/Knox'), ('America/Menominee', 'America/Menominee'), ('America/North_Dakota/Center', 'America/North_Dakota/Center'), ('America/North_Dakota/New_Salem', 'America/North_Dakota/New_Salem'), ('America/North_Dakota/Beulah', 'America/North_Dakota/Beulah'), ('America/Denver', 'America/Denver'), ('America/Boise', 'America/Boise'), ('America/Phoenix', 'America/Phoenix'), ('America/Los_Angeles', 'America/Los_Angeles'), ('America/Anchorage', 'America/Anchorage'), ('America/Juneau', 'America/Juneau'), ('America/Sitka', 'America/Sitka'), ('America/Metlakatla', 'America/Metlakatla'), ('America/Yakutat', 'America/Yakutat'), ('America/Nome', 'America/Nome'), ('America/Adak', 'America/Adak'), ('Pacific/Honolulu', 'Pacific/Honolulu')], max_length=100, null=True)),
                ('date_format', models.CharField(blank=True, max_length=50, null=True)),
                ('gratuity_baseline', models.CharField(blank=True, max_length=50, null=True)),
                ('fuel_surcharge', models.CharField(blank=True, max_length=50, null=True)),
                ('sales_tax', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Company.companyaddressmodel')),
                ('card_details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Company.paymentinfo')),
                ('company_package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Company.companypackage')),
                ('merchant_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Client.merchantaccount')),
                ('userprofile', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Account.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='companypackage',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Company.package'),
        ),
    ]
