# Generated by Django 3.2.4 on 2022-04-19 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acmi_number', models.CharField(blank=True, max_length=500, null=True)),
                ('full_name', models.CharField(blank=True, max_length=500, null=True)),
                ('non_refundable_fee', models.CharField(blank=True, max_length=500, null=True)),
                ('material_fee', models.CharField(blank=True, max_length=500, null=True)),
                ('tuition_fee', models.CharField(blank=True, max_length=500, null=True)),
                ('total_required_fee', models.CharField(blank=True, max_length=500, null=True)),
                ('paid_fee', models.CharField(blank=True, max_length=500, null=True)),
                ('outstanding_fee', models.CharField(blank=True, max_length=500, null=True)),
                ('previous_student_fee_history', models.CharField(blank=True, max_length=500, null=True)),
                ('agent_name', models.CharField(blank=True, max_length=500, null=True)),
                ('commission', models.CharField(blank=True, max_length=500, null=True)),
                ('bonus', models.CharField(blank=True, max_length=500, null=True)),
                ('total_commission_amount', models.CharField(blank=True, max_length=500, null=True)),
                ('previous_commission_history', models.CharField(blank=True, max_length=500, null=True)),
                ('phone', models.CharField(blank=True, max_length=500, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
