# Generated by Django 3.2.4 on 2022-04-19 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
