# Generated by Django 3.2.4 on 2022-04-19 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Agent', '0002_alter_agentmodel_email'),
        ('Student', '0002_studentmodel_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='agent_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Agent.agentmodel'),
        ),
    ]
