# Generated by Django 3.2.4 on 2022-04-19 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0003_alter_studentmodel_agent_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentmodel',
            old_name='bonus',
            new_name='discount',
        ),
    ]
