# Generated by Django 3.2.4 on 2022-04-19 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0004_rename_bonus_studentmodel_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='agent_bonus',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
