# Generated by Django 3.2.4 on 2022-04-19 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0005_studentmodel_agent_bonus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='commission',
            field=models.IntegerField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='discount',
            field=models.IntegerField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='material_fee',
            field=models.IntegerField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='non_refundable_fee',
            field=models.IntegerField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='outstanding_fee',
            field=models.IntegerField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='paid_fee',
            field=models.IntegerField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='total_commission_amount',
            field=models.IntegerField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='total_required_fee',
            field=models.IntegerField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='tuition_fee',
            field=models.IntegerField(blank=True, max_length=500, null=True),
        ),
    ]
