# Generated by Django 3.1.3 on 2022-04-19 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0007_auto_20220419_0217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentmodel',
            old_name='paid_fee',
            new_name='application_fee',
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
