# Generated by Django 3.1.3 on 2022-04-19 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Agent', '0006_auto_20220419_1312'),
        ('Student', '0008_auto_20220419_1249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentmodel',
            old_name='commission',
            new_name='agent_commission',
        ),
        migrations.CreateModel(
            name='PayModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_fee', models.IntegerField(blank=True, null=True)),
                ('paid_on', models.DateField(auto_now=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Agent.agentmodel')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Student.studentmodel')),
            ],
        ),
    ]
