# Generated by Django 3.1.3 on 2022-04-20 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0013_remove_studentmodel_agent_bonus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentmodel',
            old_name='paid_fee_fee',
            new_name='paid_fee',
        ),
    ]
