# Generated by Django 3.2.4 on 2022-04-22 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0014_auto_20220420_2125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentmodel',
            name='non_refundable_fee',
        ),
        migrations.AlterField(
            model_name='paymodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
