# Generated by Django 3.2.4 on 2022-04-22 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0016_auto_20220422_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymodel',
            name='paid_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
