# Generated by Django 3.2.4 on 2022-04-22 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0017_alter_paymodel_paid_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymodel',
            name='outstanding_fee',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymodel',
            name='total_required_fee',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
