# Generated by Django 3.2.4 on 2022-04-22 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0018_auto_20220422_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='quarterly_fee_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
