# Generated by Django 3.2.4 on 2022-04-23 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0020_rename_paid_fee_paymodel_fee_pay'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentmodel',
            old_name='previous_student_fee_history',
            new_name='student_fee_history',
        ),
    ]
