# Generated by Django 3.2.4 on 2022-04-23 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0022_rename_student_fee_history_studentmodel_previous_student_fee_history'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentmodel',
            old_name='previous_student_fee_history',
            new_name='history',
        ),
    ]
