# Generated by Django 3.2.4 on 2022-04-23 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0024_rename_history_studentmodel_previous_student_fee_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='last_paid_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
