# Generated by Django 3.2.4 on 2022-04-23 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0025_studentmodel_last_paid_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymodel',
            name='outstanding_fee',
        ),
        migrations.RemoveField(
            model_name='paymodel',
            name='total_required_fee',
        ),
    ]
