# Generated by Django 3.2.4 on 2022-04-24 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0026_auto_20220423_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='total_commission_paid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
