# Generated by Django 3.2.4 on 2022-04-24 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0027_studentmodel_total_commission_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='total_commission_paid',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
