# Generated by Django 3.2.4 on 2022-04-26 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0030_auto_20220424_0332'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='amount_already_inserted',
            field=models.BooleanField(default=True),
        ),
    ]
