# Generated by Django 3.2.4 on 2022-05-01 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0032_auto_20220426_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymodelstudent',
            name='fee_pay',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='outstanding_fee',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='paid_fee',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='quarterly_fee_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='total_commission_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='total_commission_paid',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='total_fee',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='total_required_fee',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
