# Generated by Django 3.2.4 on 2022-05-01 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0033_auto_20220501_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='commission_to_pay',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
