# Generated by Django 3.2.4 on 2022-05-10 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0034_studentmodel_commission_to_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymodelstudent',
            name='is_material_fee',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='discount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
