# Generated by Django 3.2.4 on 2022-06-22 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0036_auto_20220621_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='paid_fee',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
