# Generated by Django 3.2.4 on 2022-06-22 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0037_alter_studentmodel_paid_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='application_fee_paid',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
