# Generated by Django 3.2.4 on 2022-06-22 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0038_studentmodel_application_fee_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='material_fee_paid',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
