# Generated by Django 3.2.4 on 2022-06-22 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0039_studentmodel_material_fee_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymodelstudent',
            name='is_tuition_and_material_fee',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
