# Generated by Django 3.2.4 on 2022-07-19 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0002_auto_20220720_0151'),
        ('Student', '0042_alter_paymodelstudent_agent_commision_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Courses.course'),
        ),
    ]
