# Generated by Django 3.2.4 on 2022-07-20 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0044_studentmodel_refunded'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymodelstudent',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
