# Generated by Django 3.2.4 on 2022-07-20 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0045_paymodelstudent_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymodelstudent',
            name='mode_of_payment',
            field=models.CharField(blank=True, choices=[('CASH', 'CASH'), ('BANK', 'BANK')], max_length=100, null=True),
        ),
    ]
