# Generated by Django 3.2.4 on 2022-07-22 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0046_paymodelstudent_mode_of_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='refund_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
