# Generated by Django 3.2.4 on 2022-07-30 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0048_studentmodel_quarters_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='oshc',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
