# Generated by Django 3.2.4 on 2022-07-31 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0049_studentmodel_oshc'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='refund_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
