# Generated by Django 3.2.4 on 2022-08-02 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0050_studentmodel_refund_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymodelstudent',
            name='is_oshc_fee',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='paymodelstudent',
            name='mode_of_payment',
            field=models.CharField(blank=True, choices=[('CASH', 'CASH'), ('BANK TRANSFER', 'BANK TRANSFER'), ('UPFRONT FEE', 'UPFRONT FEE'), ('ADJUSTMENT', 'ADJUSTMENT')], max_length=100, null=True),
        ),
    ]
