# Generated by Django 3.2.4 on 2022-08-02 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0051_auto_20220802_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='oshc_fee_paid',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
