# Generated by Django 3.2.4 on 2022-08-07 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0053_studentmodel_refund_way'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='commission',
            field=models.IntegerField(blank=True, default=30, null=True),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='gst',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='gst_status',
            field=models.CharField(blank=True, choices=[('COMMISSION ONLY', 'COMMISSION ONLY'), ('COMMISSION + GST (10%)', 'COMMISSION + GST (10%)')], default='COMMISSION ONLY', max_length=30, null=True),
        ),
    ]
