# Generated by Django 3.2.4 on 2022-08-07 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0054_auto_20220807_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymodelstudent',
            name='commission_percentage',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
