# Generated by Django 4.2.16 on 2024-10-07 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0057_paymodelstudent_is_bonus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='gst_status',
            field=models.CharField(blank=True, choices=[('NO COMMISSION', 'NO COMMISSION'), ('COMMISSION ONLY', 'COMMISSION ONLY'), ('COMMISSION + GST (10%)', 'COMMISSION + GST (10%)')], default='COMMISSION ONLY', max_length=30, null=True),
        ),
    ]
