# Generated by Django 4.2.16 on 2024-10-15 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0059_studentmodel_archived_studentmodel_archived_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='archived_tag',
            field=models.CharField(blank=True, choices=[('COMPLETED ARCHIVE', 'COMPLETED ARCHIVE'), ('WITHDRAWAL ARCHIVE', 'WITHDRAWAL ARCHIVE'), ('REFUNDED ARCHIVE', 'REFUNDED ARCHIVE')], max_length=50, null=True),
        ),
    ]
