# Generated by Django 4.2.16 on 2024-10-23 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0003_course_months'),
        ('Student', '0060_alter_studentmodel_archived_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentmodel',
            name='course',
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='courses',
            field=models.ManyToManyField(blank=True, null=True, to='Courses.course'),
        ),
    ]
