# Generated by Django 4.2.16 on 2024-11-04 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0061_remove_studentmodel_course_studentmodel_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentmodel',
            name='application_fee',
        ),
        migrations.RemoveField(
            model_name='studentmodel',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='studentmodel',
            name='commission',
        ),
        migrations.RemoveField(
            model_name='studentmodel',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='studentmodel',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='studentmodel',
            name='gst_status',
        ),
        migrations.RemoveField(
            model_name='studentmodel',
            name='material_fee',
        ),
        migrations.RemoveField(
            model_name='studentmodel',
            name='oshc',
        ),
        migrations.RemoveField(
            model_name='studentmodel',
            name='quarterly_fee_amount',
        ),
        migrations.RemoveField(
            model_name='studentmodel',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='studentmodel',
            name='total_commission_amount',
        ),
        migrations.RemoveField(
            model_name='studentmodel',
            name='total_fee',
        ),
        migrations.RemoveField(
            model_name='studentmodel',
            name='tuition_fee',
        ),
    ]
