# Generated by Django 4.2.16 on 2024-11-04 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0005_remove_course_application_fee_remove_course_comment_and_more'),
        ('Student', '0062_remove_studentmodel_application_fee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.IntegerField(blank=True, default=0, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('commission', models.IntegerField(blank=True, default=30, null=True)),
                ('gst_status', models.CharField(blank=True, choices=[('NO COMMISSION', 'NO COMMISSION'), ('COMMISSION ONLY', 'COMMISSION ONLY'), ('COMMISSION + GST (10%)', 'COMMISSION + GST (10%)')], default='COMMISSION ONLY', max_length=30, null=True)),
                ('material_fee', models.IntegerField(blank=True, null=True)),
                ('tuition_fee', models.IntegerField(blank=True, null=True)),
                ('application_fee', models.IntegerField(blank=True, default=250, null=True)),
                ('quarterly_fee_amount', models.FloatField(blank=True, null=True)),
                ('total_fee', models.FloatField(blank=True, null=True)),
                ('oshc', models.IntegerField(blank=True, null=True)),
                ('total_commission_amount', models.FloatField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Courses.course')),
            ],
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='courses',
            field=models.ManyToManyField(blank=True, null=True, to='Student.studentcourse'),
        ),
    ]
