# Generated by Django 4.2.16 on 2024-11-04 14:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0063_studentcourse_alter_studentmodel_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcourse',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 11, 4, 14, 0, 15, 147284, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
