# Generated by Django 4.2.16 on 2024-11-04 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0064_studentcourse_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymodelstudent',
            name='student_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Student.studentcourse'),
        ),
    ]
