# Generated by Django 4.2.16 on 2024-11-11 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0065_paymodelstudent_student_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymodelstudent',
            name='is_application_fee',
        ),
        migrations.RemoveField(
            model_name='paymodelstudent',
            name='is_bonus',
        ),
        migrations.RemoveField(
            model_name='paymodelstudent',
            name='is_material_fee',
        ),
        migrations.RemoveField(
            model_name='paymodelstudent',
            name='is_oshc_fee',
        ),
        migrations.RemoveField(
            model_name='paymodelstudent',
            name='is_tuition_and_material_fee',
        ),
        migrations.AddField(
            model_name='paymodelstudent',
            name='fee_type',
            field=models.CharField(blank=True, choices=[('Tuition Fee', 'Tuition Fee'), ('Material Fee', 'Material Fee'), ('Application Fee', 'Application Fee'), ('OSHC Fee', 'OSHC Fee'), ('Bonus', 'Bonus')], max_length=100, null=True),
        ),
    ]
