# Generated by Django 4.2.16 on 2024-11-11 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0066_remove_paymodelstudent_is_application_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcourse',
            name='commission_to_pay',
            field=models.IntegerField(blank=True, default=30, null=True),
        ),
    ]
