# Generated by Django 4.2.16 on 2024-11-11 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0067_studentcourse_commission_to_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcourse',
            name='total_commission_paid',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
