# Generated by Django 4.2.16 on 2024-11-11 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0068_studentcourse_total_commission_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcourse',
            name='gst',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
    ]
