# Generated by Django 4.2.16 on 2024-11-11 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0069_studentcourse_gst'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcourse',
            name='commission_to_pay',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
