# Generated by Django 3.1.3 on 2022-04-02 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='item',
            new_name='name',
        ),
    ]
