# Generated by Django 3.1.3 on 2022-04-02 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0002_auto_20220402_1423'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='menuhead',
            new_name='menu_head',
        ),
    ]
