# Generated by Django 3.1.3 on 2022-04-02 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0003_auto_20220402_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuhead',
            name='sales_tax',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
