# Generated by Django 3.1.3 on 2022-04-02 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0004_menuhead_sales_tax'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuhead',
            name='sales_tax',
        ),
    ]
