# Generated by Django 3.1.3 on 2022-03-28 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('amount', models.FloatField(blank=True, default=0, null=True)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('purchase_date', models.DateField(null=True)),
                ('supported_date', models.DateField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_number', models.CharField(blank=True, max_length=50, null=True)),
                ('bill_date', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BillItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('tax', models.FloatField(blank=True, null=True)),
                ('discount', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChartOfAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(blank=True, choices=[('Asset', 'Asset'), ('Liability', 'Liability'), ('Expense', 'Expense'), ('Income', 'Income'), ('Equity', 'Equity')], max_length=40, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('code', models.IntegerField(blank=True, null=True)),
                ('category', models.CharField(blank=True, choices=[('Cash and Bank', 'Cash and Bank'), ('Expected Payments from Customers', 'Expected Payments from Customers'), ('Expected Payments to Vendors', 'Expected Payments to Vendors'), ('Sales Taxes', 'Sales Taxes'), ('Due for Payroll', 'Due for Payroll'), ('Other Short-Term Liability', 'Other Short-Term Liability'), ('Income', 'Income'), ('Uncategorized Income', 'Uncategorized Income'), ('Operating Expense', 'Operating Expense'), ('Payroll Expense', 'Payroll Expense'), ('Uncategorized Expense', 'Uncategorized Expense'), ('Business Owner Contribution and Drawing', 'Business Owner Contribution and Drawing'), ('Retained Earnings: Profit', 'Retained Earnings: Profit')], max_length=40, null=True)),
                ('is_enabled', models.BooleanField(default=True, null=True)),
                ('is_editable', models.BooleanField(default=True, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journal_no', models.CharField(blank=True, max_length=40, null=True)),
                ('dated', models.DateField(null=True, verbose_name='Transaction Date')),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JournalItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.FloatField(default=0, null=True)),
                ('credit', models.FloatField(default=0, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dated', models.DateField(null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('transaction_type', models.CharField(blank=True, choices=[('Deposit', 'Deposit'), ('Withdraw', 'Withdraw')], max_length=40, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_type', models.CharField(blank=True, choices=[('REGULAR', 'REGULAR'), ('INDIVIDUAL', 'INDIVIDUAL'), ('CONTRACTOR', 'CONTRACTOR')], max_length=40, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact', models.CharField(blank=True, max_length=20, null=True)),
                ('billing_name', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('billing_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('zip', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('balance', models.FloatField(blank=True, default=0, null=True)),
                ('ssn', models.CharField(blank=True, max_length=20, null=True)),
                ('ein', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
