# Generated by Django 3.1.3 on 2022-03-28 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Company', '0001_initial'),
        ('Reservation', '0001_initial'),
        ('Accounting', '0001_initial'),
        ('Client', '0002_auto_20220328_2026'),
        ('setting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Company.companyprofilemodel'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='account_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Accounting.chartofaccount'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='bill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Accounting.bill'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_category', to='Accounting.chartofaccount'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Client.personalclientprofilemodel'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Company.companyprofilemodel'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='reservation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Reservation.reservation'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Accounting.vendor'),
        ),
        migrations.AddField(
            model_name='journalitem',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Accounting.chartofaccount'),
        ),
        migrations.AddField(
            model_name='journalitem',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Company.companyprofilemodel'),
        ),
        migrations.AddField(
            model_name='journalitem',
            name='journal_entry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Accounting.journalentry'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Company.companyprofilemodel'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='reservation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Reservation.reservation'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Accounting.transaction'),
        ),
        migrations.AddField(
            model_name='chartofaccount',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Company.companyprofilemodel'),
        ),
        migrations.AddField(
            model_name='billitem',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Accounting.chartofaccount'),
        ),
        migrations.AddField(
            model_name='billitem',
            name='bill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Accounting.bill'),
        ),
        migrations.AddField(
            model_name='billitem',
            name='sales_tax',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='setting.salestax'),
        ),
        migrations.AddField(
            model_name='bill',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Company.companyprofilemodel'),
        ),
        migrations.AddField(
            model_name='bill',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Accounting.vendor'),
        ),
        migrations.AddField(
            model_name='asset',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Company.companyprofilemodel'),
        ),
    ]
