# Generated by Django 3.1.3 on 2022-03-28 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Table', '0002_remove_tablemodel_user'),
        ('Order', '0002_remove_ordermodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Table.tablemodel'),
        ),
    ]
