# Generated by Django 3.1.3 on 2022-03-31 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0003_ordermodel_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='table',
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='table_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
