# Generated by Django 3.1.3 on 2022-03-31 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Table', '0005_auto_20220331_2000'),
        ('Order', '0004_auto_20220331_1954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='table_number',
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Table.tablemodel'),
        ),
    ]
