# Generated by Django 3.1.3 on 2022-03-31 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0001_initial'),
        ('Order', '0005_auto_20220331_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Restaurant.restaurantmodel'),
        ),
    ]
