# Generated by Django 3.1.3 on 2022-03-31 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0006_ordermodel_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='bill_paid',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
