# Generated by Django 3.1.3 on 2022-03-31 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0007_ordermodel_bill_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
