# Generated by Django 3.1.3 on 2022-04-03 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0009_auto_20220331_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
