# Generated by Django 3.1.3 on 2022-03-29 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Table', '0002_remove_tablemodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablemodel',
            name='table_status',
            field=models.CharField(blank=True, choices=[('available', 'available'), ('occupied', 'occupied')], default='Available', max_length=500, null=True),
        ),
    ]
