# Generated by Django 3.1.3 on 2022-03-29 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Table', '0003_auto_20220329_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablemodel',
            name='table_status',
            field=models.CharField(blank=True, choices=[('available', 'available'), ('occupied', 'occupied')], default='AVAILABLE', max_length=500, null=True),
        ),
    ]
